source 'https://rubygems.org'

gem 'rails', '~> 3.2.8'

gem 'json', '~> 1.7.5'
gem 'simple_form', '~> 2.0.4'

gem 'sqlite3', '~> 1.3.6', :groups => [:test, :development]
gem 'pg', '~> 0.14.1', :groups => :production



# Using Capybara with RSpec:
# http://rubydoc.info/github/jnicklas/capybara#Using_Capybara_with_RSpec

group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'twitter-bootstrap-rails', '~> 2.1.4'
  end
gem 'jquery-rails', '~> 2.1.3'

group :development, :test do
  gem 'hirb', '~> 0.7.0'
  gem 'quiet_assets', '~> 1.0.1' # wylacza logowanie *assets pipeline*
  end

# alternatywa dla serwera Webrick
gem 'thin'

